### PR TITLE
Add license

### PR DESCRIPTION
**Pull request by iblue**
The software is missing a license. Since you are using CC0 in Mini-Pi, I think this could fit ProtoNTT as well.

### CODE REVIEW

**Comment by Mysticial** [comment]
I haven't decided on a license yet. But I'm currently leaning towards BSD for all of my publicly available research code.

**Comment by iblue** [comment]
What about now?

**Comment by Mysticial** [comment]
BSD3

**Comment by iblue** [comment]
:+1: Awesome!

**Pull request closed without merging**
